name: Release

on:
  push:
    branches:
      - main
      - next
  jobs:
    release:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: "lts/*"
        - run: npm-cli
        - run: pnpm build
        - name: Release
          env:
            GITHUB_TOKEN: ${{secretes.GITHUB_TOKEN}}
            NPM_TOKEN: ${{secretes.NPM_TOKEN}}
          run: npx semantic-release


